pipeline {
    agent any

    environment {
        EC2_PUBLIC_IP = '13.127.92.121' // Updated IP from Terraform output
        IMAGE_NAME = 'rauljyoti/motivation-web-app:latest'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'https://github.com/jyotiraul/Motivation-web-app.git', branch: 'main'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-cred') {
                        docker.build("${IMAGE_NAME}").push()
                    }
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ec2-ssh-key', keyFileVariable: 'KEY')]) {
                    sh """
                        ssh -o StrictHostKeyChecking=no -i $KEY ubuntu@${EC2_PUBLIC_IP} <<EOF
                        docker pull ${IMAGE_NAME}
                        docker rm -f motivation-app || true
                        docker run -d -p 5000:5000 --name motivation-app ${IMAGE_NAME}
                        EOF
                    """
                }
            }
        }
    }

    triggers {
        githubPush() // Automatically triggers on GitHub push
    }
}
