name: CI/CD - Build & Deploy to Minikube

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/motivation-app:latest ./app

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/motivation-app:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/motivation-app motivation-app=${{ secrets.DOCKER_USERNAME }}/motivation-app:latest
